window.routes = [
  {
    id: "ai-infra",
    emoji: "⚡",
    title: "路線一：AI 基礎建設與算力生態",
    color: "#FF6B35",
    accent: "#FFA07A",
    subtitle: "從晶片到資料中心的完整 AI 堆疊",
    pm: "評估 AI 算力供應鏈瓶頸與機會點，判斷哪些基礎建設元件將成為下一個產品差異化關鍵",
    da: "收集各廠算力效能指標（TOPS/W、TCO、推理成本）的量化差異，建立競品 benchmark 資料庫",
    flow: [
      { step: "09:00", action: "南港二館 7F → NVIDIA Keynote 準備區報到（若 6/1 已聽 GTC Keynote，可直接進展區）" },
      { step: "09:30", action: "南港一館 → 台達電 / 緯穎 / 鴻海 AI 伺服器展區（花 2 小時深看）" },
      { step: "11:30", action: "南港一館 → 力積電 3D AI Foundry 展區" },
      { step: "13:00", action: "午餐（南港館 B1 美食街或一館周邊）" },
      { step: "13:30", action: "南港二館 7F → Intel CEO 陳立武 Keynote（6/2 當天）" },
      { step: "15:00", action: "TICC → NVIDIA GTC 展區（Vera Rubin 實機、Jetson Thor）" },
      { step: "16:30", action: "南港一館 → 研華 Edge AI 展區（K0603a 攤位）" },
    ],
    venues: [
      {
        name: "NVIDIA",
        hall: "TICC 台北國際會議中心（獨家租用）+ 台北流行音樂中心",
        booth: "TICC 全館 / GTC Taipei 展區",
        demos: [
          "Vera Rubin NVL72 機架級 AI 超級電腦實機展示 — 連接 36 顆 Vera CPU + 72 顆 Rubin GPU，採第六代 NVLink",
          "Jetson Thor 邊緣 AI 平台 — 基於 Blackwell 架構，2070 FP4 TFLOPS，功耗 40-130W 可調",
          "Alpamayo 自駕車開放平台 — 已獲 BC Award 智慧車類別獎",
          "DLSS 5 神經渲染技術展示",
          "NVIDIA × MediaTek 聯名 Arm 架構消費級處理器（首度亮相）",
          "Physical AI demo：Isaac 機器人平台、Omniverse 數位孿生",
          "NemoClaw AI 機械手臂（與威剛合作展出）",
        ],
        why: "黃仁勳已於 5/23 提前抵台，6/1 上午 11:00 於台北流行音樂中心發表 GTC Keynote。Vera Rubin 訓練效能為 Blackwell 的 3.5 倍、推理效能 5 倍、推理成本降至 1/7。TICC 為 NVIDIA 獨家場地，GTC Taipei 6/1-6/4 同步展開，議題涵蓋 AI 工廠、Physical AI、Agentic AI。",
        questions: [
          "Vera Rubin NVL72 的無纜線、無管線、無風扇模組化設計，每個計算托盤組裝時間從 2 小時縮短至 5 分鐘，這對資料中心部署時間與人力成本的影響？",
          "100% 液冷架構可在攝氏 45 度運行，代表可用環境空氣乾式冷卻器——這對台灣散熱供應鏈（雙鴻、奇鋐）的產品規格要求有何改變？",
          "ConnectX-9 SuperNIC + Spectrum-X 矽光一體封裝交換機的量產時程？",
          "NVIDIA × MediaTek Arm 消費處理器的目標市場與效能定位？和 Qualcomm Snapdragon X 的差異？",
          "Jetson Thor 的邊緣部署案例中，哪些場域已有客戶付費？",
        ],
      },
      {
        name: "Intel 英特爾",
        hall: "南港展覽館 2 館 7F + 世貿一館機器人區 + 信義區活動",
        booth: "南港二館 Keynote / 世貿一館機器人展區",
        demos: [
          "CEO 陳立武 6/2 下午 13:30 Keynote — 矽晶×系統×軟體三位一體新願景",
          "Core Ultra Series 3 處理器驅動的機器人與邊緣 AI 展示",
          "與研揚 AAEON、研華、華碩、NEXCOM、超恩 Vecow、Orisol、VinRobotics 合作的人型機器人 / 機器手臂 / AI 工業電腦",
          "Intel Foundry 先進製程與晶圓代工進展",
          "AI PC 平台與 Arc GPU 專業顯卡",
        ],
        why: "陳立武（Lip-Bu Tan）上任後首次 COMPUTEX，外界高度關注 Intel Foundry 製程藍圖、AI PC 反攻策略。Intel 在世貿一館機器人區有大量合作展示，部分活動移師信義區顯示展會外溢。Intel CEO Keynote 已報名額滿。",
        questions: [
          "Intel Foundry 18A 製程進展，與台積電 N3/N2 的良率差距？",
          "Core Ultra Series 3 的 NPU 效能（TOPS）在實際推理場景中的延遲表現？",
          "Intel 與研揚等台灣夥伴的機器人合作，是客製 SoC 還是標準平台？授權模式？",
          "AI PC 出貨 guidance 與市場佔有率目標？",
        ],
      },
      {
        name: "緯穎（6669）",
        hall: "南港展覽館",
        booth: "南港展區（具體攤位號請現場確認）",
        demos: [
          "NVIDIA Vera Rubin NVL72 全液冷機櫃級解決方案（與緯創共同開發，首批供應商之一）",
          "AMD Helios 機架級解決方案",
          "CPO 光學擴展機櫃設計 — 整合 Ayar Labs TeraPHY™ 光學引擎 + GUC 2.5D 先進封裝 AI ASIC",
          "ELSFP SuperNova™ 遠端光源 + 自研液冷解決方案",
          "800V HVDC（高壓直流電）端對端系統 — 攜手台達電 + TE Connectivity",
        ],
        why: "緯穎是全球雲端資料中心 IT 基礎設備的核心 ODM，是 NVIDIA Vera Rubin NVL72 首批供應商之一。展示的四大技術軸線（AI 運算、液冷、光互連、HVDC 供電）完整呈現次世代資料中心的設計方向。緯穎每股配發 165 元股利，反映其 AI 伺服器業務的爆發力。",
        questions: [
          "Vera Rubin NVL72 的液冷方案良率？大量出貨的瓶頸在哪？",
          "CPO 光學擴展的商用時程？目前是 PoC 還是已進入量產驗證？",
          "800V HVDC 相較傳統 48V 的建置成本差異？雲端客戶的採用意願？",
          "從 Blackwell → Vera Rubin，機櫃設計需要哪些重新工程化？",
        ],
      },
      {
        name: "鴻海（2317）",
        hall: "南港展覽館 1 館",
        booth: "南港一館（大型展區）",
        demos: [
          "AI 伺服器整機、液冷散熱方案、高密度資料中心架構",
          "工業機器人 / 機器手臂 / AMR 自動搬運機器人",
          "AI 工廠解決方案（智慧製造產線）",
          "MIH 電動車平台：車用電子、智慧座艙、電池管理系統",
        ],
        why: "鴻海是全球最大伺服器供應商，NVIDIA、AMD、Intel 都是合作夥伴。COMPUTEX 是觀察鴻海從「代工」轉型「智慧製造 + AI 系統整合商」的最佳窗口。",
        questions: [
          "AI 伺服器營收佔整體伺服器營收比重？YoY 成長率？",
          "液冷方案自製率有多少？哪些零組件仍需外購？",
          "AI 工廠方案在自家工廠的部署進度？ROI 數據？",
          "MIH 平台目前有幾家車廠簽約？量產車款時程？",
        ],
      },
      {
        name: "力積電（6770）",
        hall: "南港展覽館",
        booth: "南港展區",
        demos: [
          "3D AI Foundry 主題展區",
          "3D WoW（Wafer-on-Wafer）DRAM 堆疊技術",
          "IPD（Si-Cap）、Interposer 先進封裝關鍵零組件",
          "與愛普、晶豪科、Zentel Japan、智成、力晶微元合作展示 3D WoW 晶圓堆疊 IP",
          "AI 無人機（利翔航太）、智慧駕駛（瑞相）、AI EDA（智慧記憶）應用展示",
        ],
        why: "力積電是全球少數同時擁有邏輯與記憶體製程的晶圓代工廠，以成熟製程 28/40nm 結合 3D 堆疊達到接近先進製程的效能，鎖定邊緣 AI 市場。這是不走台積電路線的差異化典型案例。",
        questions: [
          "3D WoW 堆疊的良率目前到什麼水準？與 HBM 的定位差異？",
          "成熟製程 + 3D 堆疊的 cost per TOPS 相較先進製程方案的優勢幅度？",
          "Fab IP 授權模式（如印度塔塔）的進展？已簽幾個海外合作案？",
        ],
      },
      {
        name: "研華 Advantech（2395）",
        hall: "南港展覽館一館 K0603a",
        booth: "K0603a",
        demos: [
          "Edge Computing & AI-Powered WISE Solutions 品牌主題展",
          "WEDA 開發者架構 — 跨晶片邊緣 AI 平台",
          "Digital Twin + AI Agent 工業應用 demo",
          "6/4 COMPUTEX Forum 專題演講：Physical AI 從概念到產業落地",
          "首度整合全球合作夥伴大會（WPC）與 COMPUTEX",
        ],
        why: "研華董事長劉克振罕見談 5 年藍圖，宣布從工業電腦轉型 AI 時代工業應用平台。研華深化與 NVIDIA 合作，是觀察「邊緣 AI 如何從概念走向工廠現場」的最佳標的。",
        questions: [
          "WEDA 架構的客戶採用數量？從 PoC 到量產的轉換率？",
          "Edge AI 方案的 ASP 相較傳統工控產品的溢價幅度？",
          "AI Agent 在製造業場景的具體應用案例與效益數據？",
        ],
      },
    ],
  },
  {
    id: "ai-edge",
    emoji: "📱",
    title: "路線二：Edge AI 與 AI PC 終端落地",
    color: "#4ECDC4",
    accent: "#7EDDDE",
    subtitle: "AI 從雲端走進你的裝置",
    pm: "評估 on-device AI 的成熟度與殺手級應用，判斷用戶的真實痛點是否被解決，AI PC 是否已找到 PMF",
    da: "比較各平台 NPU 性能、功耗比、實際應用延遲與準確率，追蹤 AI 筆電銷售佔比與 ASP 溢價",
    flow: [
      { step: "09:30", action: "南港一館 → 華碩、宏碁、微星 AI PC 展區（各花 40 分鐘體驗實機）" },
      { step: "12:00", action: "南港二館 → 高通展區（Snapdragon X 平台深度了解）" },
      { step: "13:00", action: "午餐" },
      { step: "14:00", action: "南港 → 聯發科展區（Dimensity AI 晶片、端側 LLM）" },
      { step: "15:30", action: "南港一館 → 威剛 ADATA 展區（AI PC 記憶體、PCIe Gen5 SSD）" },
      { step: "16:30", action: "南港一館 → 技嘉 / 華擎（主機板 + AI 桌機）" },
    ],
    venues: [
      {
        name: "Qualcomm 高通",
        hall: "南港展覽館 2 館 7F",
        booth: "Keynote 區 + 展示區",
        demos: [
          "CEO Cristiano Amon 6/1 下午 14:00 開幕 Keynote — Agentic AI × 邊緣運算",
          "Snapdragon X 系列 AI PC 平台最新進展",
          "Dragonwing 工業 AI / 機器人邊緣平台",
          "端側代理式 AI（Agentic AI）工作負載展示",
          "裝置端 AI 模型推理（7B+ 參數）即時 demo",
        ],
        why: "高通是 Arm 架構 AI PC 的開拓者，Snapdragon X 已進入第二代。Amon 將聚焦 AI 運算普及化，從手機到 PC 到工業邊緣。PChome 統計 AI 筆電銷量年增兩成以上，佔比近四成，高通是背後關鍵推手。",
        questions: [
          "Snapdragon X 第二代的 NPU TOPS 提升幅度？vs Intel Core Ultra Series 3？",
          "ISV 軟體相容性覆蓋率現在到多少？哪些關鍵應用仍缺？",
          "Agentic AI 在端側的記憶體最低需求？7B 模型的 token/s 速度？",
          "Dragonwing 在工業場景的 design-win 案例數量？",
        ],
      },
      {
        name: "聯發科 MediaTek（2454）",
        hall: "南港展覽館",
        booth: "展區 + Forum 演講",
        demos: [
          "Dimensity 系列行動 AI 晶片最新方案",
          "Kompanio 系列 Chromebook/平板 AI 平台",
          "端側生成式 AI 解決方案（Agentic AI）",
          "與 NVIDIA 合作的 Arm 架構消費處理器（可能首度展示）",
          "與元太合作的生成式 AI 電子閱讀器 SoC — 離線翻譯、語音轉逐字稿、AI 摘要",
        ],
        why: "聯發科在行動 AI 晶片名列第一梯隊，2026 年主打 Agentic AI。與 NVIDIA 合作的 Arm 消費處理器是今年最大驚喜。與元太合作的 AI 電子閱讀器 SoC 是 AI 落地的細分場景案例。蔡力行原定 Keynote 已取消，但展區仍是必看。",
        questions: [
          "NVIDIA × MediaTek Arm 處理器的目標 TDP 與效能定位？何時量產？",
          "聯發科在 AI PC 市場的正式進入時程？還是先聚焦 Chromebook？",
          "端側 LLM 的 token 生成速度 benchmark？與高通的差異？",
          "AI 電子閱讀器 SoC 的客戶管道？量產規模預期？",
        ],
      },
      {
        name: "華碩 ASUS / ROG",
        hall: "南港展覽館 1 館 & 2 館",
        booth: "大型品牌展區",
        demos: [
          "AI 筆電完整產品線：Copilot+ PC、ExpertBook Ultra 商用 AI 筆電",
          "ExpertBook Ultra 循環經濟設計 — 50% 回收鋁鎂合金、模組化維護",
          "ROG Lab 電競 × AI 融合裝備",
          "AI 基礎架構方案（企業端 AI 部署）",
          "AI 邊緣運算 + IoT 產品線",
        ],
        why: "華碩 ExpertBook Ultra 聚焦循環經濟設計，是 ESG × AI 結合的典範。ROG 電競品牌是高 ASP 產品線。PChome 數據顯示華碩名列 AI 筆電熱銷榜前三名。",
        questions: [
          "AI PC 目前佔整體 PC 出貨的百分比？下半年 guidance？",
          "消費者最常實際使用的 AI 功能前 3 名？使用頻率數據？",
          "Copilot+ PC 的 ASP 溢價 vs 非 AI 機種？",
          "循環經濟設計在 B2B 標案中是否已成為加分項？",
        ],
      },
      {
        name: "宏碁 Acer / 微星 MSI / 技嘉 GIGABYTE",
        hall: "南港展覽館 1 館",
        booth: "各自品牌展區",
        demos: [
          "宏碁：Swift 16 AI、Swift Edge 輕薄 AI 筆電（<1kg）、Predator 電競 + RTX 50 系列",
          "微星：Claw 8 AI+ 電競掌機、AI 筆電產品線、GS63 獲 BC Award",
          "技嘉：AI 主機板（獲 BC Award）、AI 桌機、顯示卡方案",
          "威剛 ADATA：XPG NOVAKEY RGB DDR5（8000MT/s）、PCIe Gen5 SSD、AI PC 記憶體（南港展區）",
        ],
        why: "品牌端是 AI 技術落地消費市場的第一線。CES 2026 各家已發布新品，COMPUTEX 是亞太首次大規模實機體驗。各品牌的產品策略差異值得比較：宏碁走穩健 Copilot+ 全面佈局，微星強調電競掌機差異化，技嘉聚焦主機板與 DIY 生態。",
        questions: [
          "AI PC 換機潮是否已啟動？各品牌的通路庫存水位？",
          "Arm 架構 AI PC vs x86 的銷售佔比變化趨勢？",
          "DDR5 8000MT/s 在 AI 工作負載中的實測效能提升幅度？",
        ],
      },
    ],
  },
  {
    id: "robotics",
    emoji: "🤖",
    title: "路線三：AI 機器人與 Physical AI",
    color: "#9B59B6",
    accent: "#C39BD3",
    subtitle: "首屆機器人專館 × Physical AI 的 ChatGPT 時刻",
    pm: "判斷機器人在哪些垂直場景最接近 PMF，從 demo 到量產的差距有多大，哪些是可投入的商業機會",
    da: "量化機器人任務成功率、操作延遲、單台部署成本，評估 Physical AI 市場規模預測的可信度",
    flow: [
      { step: "09:30", action: "世貿一館 → AI 機器人專區（花 2.5 小時完整走一圈）" },
      { step: "12:00", action: "世貿一館會議室 → 當日機器人 / Physical AI 論壇（NXP、NVIDIA、ABB 等）" },
      { step: "13:30", action: "搭捷運至南港（約 20 分鐘）" },
      { step: "14:00", action: "南港二館 7F → NXP CEO Keynote（6/2 下午）" },
      { step: "15:30", action: "TICC → NVIDIA Jetson Thor / Isaac 機器人平台展示" },
      { step: "16:30", action: "南港一館 → 鴻海 AMR / AI 工廠展示" },
    ],
    venues: [
      {
        name: "世貿一館 AI 機器人專區（首屆）",
        hall: "世貿一館",
        booth: "AI 機器人區（大型主題展區）",
        demos: [
          "上銀科技：雙臂機器手、行星滾柱螺桿新品、與美國新創合作的物流機器人（首度亮相）",
          "聰泰科技：AI 視覺感測 × 機器人整合方案",
          "所羅門：3D AI 視覺引導自動化系統",
          "女媧創造 + 遊戲橘子：Kebbi 3、Collibot、N300 機器人 + Vyin AI 機器人大腦",
          "永彰科技：高精密減速機",
          "宇隆科技：機器人精密零組件",
          "德州儀器 TI：機器人馬達驅動與感測方案",
          "Intel 機器人展示區：Core Ultra 驅動的人型機器人、AI 工業電腦（與研揚、NEXCOM、超恩等合作）",
        ],
        why: "世貿一館首設 AI 機器人專區，集結 180+ 家廠商，涵蓋從感測器、馬達、減速機到系統整合的完整供應鏈。Counterpoint Research 預估 2025-2035 年 Physical AI 累計出貨量達 1.45 億台。這是全亞洲規模最大的機器人 × AI 整合展示。",
        questions: [
          "上銀的雙臂機器手在哪些場景已有 PoC？精度與重複定位誤差數據？",
          "女媧 Kebbi 3 + Vyin AI 的「AI 機器人大腦」能做到什麼程度的自主決策？",
          "所羅門 3D AI 視覺的物件辨識準確率？在不同光線環境下的穩定性？",
          "Intel Core Ultra 驅動的機器人 vs NVIDIA Jetson 平台的效能/成本比較？",
          "這些機器人 demo 中，有幾個已有「付費客戶」而非只是 PoC？",
        ],
      },
      {
        name: "NXP 恩智浦半導體",
        hall: "南港展覽館 2 館 7F",
        booth: "Keynote 區 + 展示區",
        demos: [
          "CEO Rafael Sotomayor 6/2 下午 Keynote — Physical AI 主題",
          "車用 AI MCU/MPU 最新方案",
          "邊緣智慧控制器 × 工業自動化",
          "機器人安全認證晶片方案",
        ],
        why: "NXP 是車用與工業 MCU/MPU 全球龍頭，他們定義的 Physical AI 概念——AI 從數位世界走入實體控制——與 NVIDIA 的敘事形成有趣對比。NXP 代表的是「小算力、高可靠、即時反應」的 AI 路線。",
        questions: [
          "NXP 定義的 Physical AI 與 NVIDIA 的 Physical AI 有何本質差異？",
          "車用 AI 晶片的安全認證（ASIL-D）取得進展？與 Tier-1 的合作名單？",
          "低功耗 AI 控制器的 inference latency 在毫秒級的表現？",
        ],
      },
    ],
  },
  {
    id: "next-gen",
    emoji: "🔬",
    title: "路線四：次世代科技與先進封裝",
    color: "#E74C3C",
    accent: "#F1948A",
    subtitle: "CoWoS、HBM、矽光子、CPO 與 6G",
    pm: "判斷哪些「次世代」技術已接近商用轉折點，評估技術成熟度與產品整合時機",
    da: "追蹤先進封裝良率、HBM 頻寬成本比、光互連損耗率、6G 頻譜效率等前瞻數據",
    flow: [
      { step: "09:30", action: "南港一館 → 半導體及先進技術區（力積電、封裝廠商）" },
      { step: "11:00", action: "南港展區 → 緯穎 CPO 光互連展示（Ayar Labs 合作）" },
      { step: "12:00", action: "午餐" },
      { step: "13:00", action: "南港二館 → Marvell CEO Keynote（注意：時間已調整，請留意公告）" },
      { step: "14:30", action: "南港 → 先進通訊及網路產品區（5G 專網、6G）" },
      { step: "16:00", action: "南港一館 → 零組件及先進電源技術區" },
    ],
    venues: [
      {
        name: "Marvell 邁威爾科技",
        hall: "南港展覽館 2 館 7F",
        booth: "Keynote 區",
        demos: [
          "CEO Matt Murphy Keynote（時間已調整，注意大會公告）",
          "客製化 AI 加速器（Custom Silicon for Hyperscalers）",
          "800G / 1.6T 資料中心交換晶片",
          "CPO（共同封裝光學）解決方案",
        ],
        why: "Marvell 是 AI 資料中心的隱形冠軍，為雲端巨頭提供客製化 ASIC 與高速互連。在 NVIDIA GPU 之外，Custom ASIC 是 AI 推理成本優化的重要路徑。",
        questions: [
          "Custom AI ASIC vs NVIDIA GPU 在特定推理場景的 TCO 差異？",
          "1.6T 交換晶片的量產時程？誰是第一批客戶？",
          "CPO 方案的功耗節省比例？與矽光子方案的競合關係？",
        ],
      },
      {
        name: "半導體 / 先進封裝 / 通訊展區",
        hall: "南港展覽館 1 館 & 2 館",
        booth: "各展區分散",
        demos: [
          "CoWoS、3D IC、Fan-out 等先進封裝展示",
          "HBM 高頻寬記憶體方案",
          "矽光子互連模組",
          "5G 專網方案（製造業場景）",
          "6G 前瞻技術（THz、RIS、語意通訊）",
          "LEO 低軌衛星通訊與非地面網路",
        ],
        why: "AI 算力提升已不只靠製程微縮，先進封裝（CoWoS 產能）是 AI 晶片交貨的最大瓶頸。1.6T 高速傳輸標準正在確立。理解封裝 + 互連 = 理解 AI 硬體的供給面瓶頸。",
        questions: [
          "CoWoS 產能利用率目前多少？擴產時程？",
          "HBM4 vs HBM3e 的頻寬提升 vs 成本增加比例？",
          "矽光子在資料中心互連的實測損耗率？vs 傳統銅線？",
          "5G 專網在台灣製造業的部署案例數？ROI 數據？",
        ],
      },
    ],
  },
  {
    id: "startup",
    emoji: "🚀",
    title: "路線五：新創 × AI 應用 × 電子紙生態",
    color: "#2ECC71",
    accent: "#82E0AA",
    subtitle: "InnoVEX 新創展 + 世貿 AI 應用體驗館",
    pm: "發掘大公司忽略的利基需求，評估哪些新創值得合作或投資，觀察 12-18 個月後的趨勢方向",
    da: "收集新創的 traction 指標（用戶數、ARR、留存率），分析技術主題分布變化，量化市場規模假設",
    flow: [
      { step: "09:30", action: "南港二館 → InnoVEX 新創展區（花 2 小時，重點看 NVIDIA Inception + 國家館）" },
      { step: "11:30", action: "InnoVEX → 新創競賽 Pitch 觀摩（看評審問什麼問題）" },
      { step: "12:30", action: "午餐" },
      { step: "13:30", action: "搭捷運至世貿一館（約 20 分鐘）" },
      { step: "14:00", action: "世貿一館 → 電子紙產業專區（元太 + 夏普 + 振曜）" },
      { step: "15:00", action: "世貿一館 → 科技應用暨體驗館 TechXperience" },
      { step: "16:00", action: "世貿一館 → E Ink ePaper Industry Forum 2026（6/3 當天，12+ 場演講）" },
    ],
    venues: [
      {
        name: "InnoVEX 新創展區",
        hall: "南港展覽館 2 館",
        booth: "InnoVEX 專區",
        demos: [
          "NVIDIA Inception 加速器專區 — AI 新創群展",
          "時代基金會、Starfab 等加速器陣容",
          "多國國家館：法國、以色列、巴西、澳洲、泰國、菲律賓、波蘭、比利時、捷克",
          "新創競賽 Pitch 決賽（評審含國家級資本與半導體巨頭）",
        ],
        why: "InnoVEX 是亞洲最具指標性的新創展，今年評審陣容升級至國家級資本與半導體巨頭。以色列 / 法國館是 deep tech 新創的集中地。觀察新創的技術方向分布變化是預判未來趨勢的領先指標。",
        questions: [
          "今年申請最多的新創類別前 3 名是什麼？vs 去年的變化？",
          "NVIDIA Inception 進駐的新創中，有幾家已有 ARR > $1M？",
          "以色列館的新創聚焦哪些技術？有無國防科技轉民用的案例？",
          "評審最常問的問題變了嗎？反映了投資人關注點的什麼轉變？",
        ],
      },
      {
        name: "世貿一館 電子紙 + AI 應用體驗",
        hall: "世貿一館",
        booth: "電子紙產業專區 + TechXperience 科技體驗館",
        demos: [
          "元太科技：32 吋全彩 Color ePaper 數位看板（大會現場實際使用）",
          "元太 × 聯發科：AI 電子閱讀器（離線翻譯、語音轉逐字稿、AI 摘要、手寫筆記）",
          "夏普：電子紙海報系統",
          "振曜：電子紙終端裝置",
          "低碳智慧電子標籤 + 無藍光醫療顯示方案",
          "6/3 E Ink ePaper Industry Forum 2026 — 12+ 場專題演講（智慧零售、數位廣告案例）",
          "TechXperience 沉浸式科技體驗區 — AI × 垂直產業解決方案",
        ],
        why: "電子紙是台灣獨有的強勢產業，元太市占率超過 9 成。AI + 電子紙的結合開啟了全新的商業場景（智慧零售、交通、醫療顯示）。世貿一館定位為「應用端」，可看到 AI 技術的 B2B 落地樣貌。",
        questions: [
          "全彩電子紙在零售場景的佈署成本 vs LCD 看板？能源節省比例？",
          "AI 電子閱讀器的目標 ASP？消費者願付價格？",
          "電子紙在醫療顯示的法規認證進度？",
          "元太的客戶從 PoC 到規模佈署的平均週期？",
        ],
      },
    ],
  },
];

window.analystRoute = {
  title: "產業分析師專屬路線",
  description: "為 Gartner、IDC、TrendForce、MIC 機構研究員或券商科技分析師設計。重點不在產品體驗，而在「訊號捕捉」——從廠商的展示內容、措辭變化、攤位大小、人潮密度中推測產業動向與訂單能見度。",
  schedule: [
    {
      day: "6/1（展前日）— 鎖定 CEO 敘事框架",
      items: [
        { time: "11:00", event: "黃仁勳 GTC Keynote @ 台北流行音樂中心", note: "記錄「partner」一詞出現次數與指向對象、架構圖中台灣供應鏈的曝光頻率、Vera Rubin 量產時程的措辭（on track / ahead / ramp）" },
        { time: "14:00", event: "高通 CEO Keynote @ 南港二館 7F", note: "對比高通與 NVIDIA 在 Edge AI 敘事差異。高通是否有意進攻資料中心？Dragonwing 工業平台是否提及具體客戶？" },
        { time: "16:00", event: "NVIDIA 展區快速巡場 @ TICC", note: "觀察 Vera Rubin 實機旁的排隊人潮密度，問現場工程師「什麼時候可以下單」" },
      ],
    },
    {
      day: "6/2（開展首日）— 巨頭訊號 + 機器人真實度",
      items: [
        { time: "09:30", event: "南港一館快速巡場", note: "30 分鐘走一圈：攤位大小排名、哪些新面孔出現、哪些老面孔縮小或消失、人流集中在哪個展區" },
        { time: "10:30", event: "緯穎 + 鴻海展區 @ 南港一館", note: "問「Vera Rubin NVL72 訂單能見度到第幾季？」「液冷方案的供應商是否出現新面孔？」" },
        { time: "13:30", event: "Intel CEO 陳立武 Keynote @ 南港二館 7F", note: "聽 Foundry 進展措辭（是 on track 還是 ahead of schedule？）、製程命名是否再次更改、AI PC 市佔目標是否鬆口" },
        { time: "15:00", event: "NXP CEO Keynote", note: "Physical AI 定義權之爭：NXP（低功耗即時控制）vs NVIDIA（大算力模擬）各自如何框架市場" },
        { time: "16:30", event: "世貿一館機器人專區", note: "關鍵判斷：機器人是否真的有人圍觀互動？有 live demo 還是只有影片？有幾家能說出「付費客戶」？" },
      ],
    },
    {
      day: "6/3-6/4 — 供應鏈深度訪談 + 趨勢交叉驗證",
      items: [
        { time: "全天", event: "鎖定 5-8 家中型供應鏈廠商深度訪談", note: "散熱（雙鴻、奇鋐）、CCL/PCB（欣興）、連接器（TE Connectivity）、記憶體（威剛）：問「訂單能見度到第幾季？」「AI 營收佔比？」「客戶是否有新平台 NRE 訂單？」「缺料項目？」" },
        { time: "下午", event: "InnoVEX 新創巡禮 + E Ink Forum", note: "觀察新創技術方向分布：今年是 AI agent 多還是 robotics 多？是否出現生物科技 × AI 交叉趨勢？電子紙 Forum 聽實際部署案例與 ROI 數據" },
        { time: "傍晚", event: "研華 WPC 合作夥伴大會場邊交流", note: "Edge AI 的通路模式：研華如何說服傳統工廠客戶買 AI 方案？成功率多高？" },
      ],
    },
    {
      day: "6/5（最後一天）— 收尾驗證 + 報告起草",
      items: [
        { time: "全天", event: "帶著前幾天觀察回訪 2-3 個攤位做深入追問", note: "整理筆記的核心問題：「這屆和去年最大的不同是什麼？」「哪個趨勢被高估？哪個被低估？」「3 個月後回看，哪件事最重要？」" },
      ],
    },
  ],
  metrics: [
    "NVIDIA / AMD / Intel 各自的 AI 營收佔比 YoY 成長率與下半年 guidance",
    "CoWoS / HBM 產能利用率與交期變化（問台達、緯穎、力積電的供應端感受）",
    "AI 伺服器 ODM（緯穎、鴻海、廣達）的訂單能見度（季度數）",
    "Edge AI 晶片（高通、聯發科、NXP）的 design-win pipeline",
    "機器人方案的 PoC 案例數量 vs 付費量產案例數量（差距越大 = 泡沫越大）",
    "新創展區各技術主題攤位佔比的 YoY 變化（趨勢領先指標）",
    "1.6T 光模組 / CPO 的量產進度與定價趨勢",
    "AI PC 銷售佔比（PChome 數據：已近四成，追蹤是否持續攀升）",
  ],
};

window.keynotes = [
  { time: "6/1 11:00", speaker: "黃仁勳", company: "NVIDIA", venue: "台北流行音樂中心", color: "#76B900", topic: "Vera Rubin 平台 / Five-Layer Cake / Physical AI" },
  { time: "6/1 14:00", speaker: "Cristiano Amon", company: "Qualcomm", venue: "南港二館 7F", color: "#3253DC", topic: "Agentic AI / Edge 運算 / Dragonwing" },
  { time: "6/2 13:30", speaker: "陳立武", company: "Intel", venue: "南港二館 7F", color: "#0071C5", topic: "矽晶×系統×軟體 / Foundry 新願景" },
  { time: "6/2 下午", speaker: "Rafael Sotomayor", company: "NXP", venue: "南港二館 7F", color: "#FFB81C", topic: "Physical AI / 車用邊緣智慧" },
  { time: "時間調整中", speaker: "Matt Murphy", company: "Marvell", venue: "南港二館 7F", color: "#C2002F", topic: "Custom AI Silicon / 資料中心互連" },
  { time: "展期間", speaker: "蔡力行", company: "MediaTek", venue: "展區展示", color: "#E6007A", topic: "Agentic AI / 端側 LLM / NVIDIA 合作" },
  { time: "展期訪台", speaker: "蘇姿丰", company: "AMD", venue: "百億美元投資台灣", color: "#ED1C24", topic: "Helios 機架方案 / 先進封裝合作" },
];